---

- hosts: webservers

  become: yes
  remote_user: ubuntu

  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
      
    - name: copy the files 
      template: src: /var/lib/jenkins/workspace/testpipe/index.html.j2 dest: /var/www/html/index.html
      notify:
        - Restart apache
        
    handlers:
      - name: restert apapche2
          name: apache2
          state: started
     
